// ============================================================
// lib/fantasy/espnLoader.ts
//
// Loads live matchup state from ESPN Fantasy API + EROSP projections.
// Returns MatchupState[] ready for simulation.
//
// Data sources:
//   - ESPN API: current matchup pairs, team scores, roster, lineup status
//   - data/erosp/latest.json: per-player projections (primary projection signal)
//   - data/current/2026.json: team names / metadata fallback
// ============================================================

import * as fs from "fs";
import * as path from "path";
import { createESPNClient } from "../espn-api";
import type {
  EROSPPlayerData,
  FantasyTeamMatchupState,
  LeagueConfig,
  MatchupConfig,
  MatchupState,
  PlayerProjectionInput,
  PlayerRole,
  ScheduledGame,
} from "./types";
import {
  CBA_PITCHER_START_CAP,
  CBA_ROSTER_SLOTS,
  CBA_SCORING,
  ESPN_LEAGUE_ID,
  ESPN_SEASON_ID,
  GAME_SCHEDULED_PROB,
  HITTER_P_PLAY_DEFAULT,
  MATCHUP_WEEK_LENGTH_DAYS,
  RP_APPEARANCE_RATE_DEFAULT,
  SP_DAYS_BETWEEN_STARTS,
  SP_START_RATE_PER_GAME,
} from "./constants";
import { fetchLeagueSchedule, type MLBGameSlot } from "./mlbSchedule";

// ---- EROSP JSON shape ----

interface RawEROSPPlayer {
  mlbam_id: number;
  espn_id: string;
  name: string;
  position: string;
  mlb_team: string;
  role: string; // "H" | "SP" | "RP"
  fantasy_team_id: number;
  is_fa: boolean;
  erosp_raw: number;
  erosp_startable: number;
  erosp_per_game: number;
  games_remaining: number;
  start_probability: number;
  cap_factor: number;
  pa_per_game?: number;
  fp_per_pa?: number;
}

interface RawEROSPFile {
  generated_at: string;
  season: number;
  players: RawEROSPPlayer[];
}

// ---- ESPN API shapes (loosely typed) ----

type ESPNAny = Record<string, unknown>;

// ---- Helpers ----

function toRole(espnDefaultPositionId: number): PlayerRole {
  if (espnDefaultPositionId === 1) return "starting_pitcher";
  if (espnDefaultPositionId === 11) return "relief_pitcher";
  return "hitter";
}

function normalizeName(name: string): string {
  return name
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z ]/g, "")
    .trim();
}

function toISODate(d: Date): string {
  return d.toISOString().slice(0, 10);
}

/**
 * Returns the number of remaining calendar days in the current scoring week
 * (Monday through Sunday), inclusive of today.
 *
 * Used as a fallback when ESPN scoring period data isn't available.
 * Monday=7, Tuesday=6, ..., Sunday=1, after-Sunday-midnight=0
 */
function daysRemainingInCalendarWeek(now: Date = new Date()): number {
  const dayOfWeek = now.getDay(); // 0=Sun, 1=Mon ... 6=Sat
  // Days until end-of-Sunday (0=already Sunday end, 1=Saturday, ..., 6=Monday)
  const daysToSunday = dayOfWeek === 0 ? 0 : 7 - dayOfWeek;
  return daysToSunday + 1; // +1 because today still has games
}

// ---- Cached schedule config (data/fantasy/schedule-{year}.json) ----

interface ScheduleConfig {
  generatedAt: string;
  seasonId: string;
  matchupPeriods: Record<string, number[]>;
}

/**
 * Loads the pre-fetched ESPN schedule config from disk.
 * Generated by `npx tsx scripts/fetch-schedule-config.ts`.
 * Returns null if the file doesn't exist yet.
 */
function loadScheduleConfig(seasonId: string): ScheduleConfig | null {
  const configPath = path.join(process.cwd(), "data", "fantasy", `schedule-${seasonId}.json`);
  if (!fs.existsSync(configPath)) return null;
  try {
    return JSON.parse(fs.readFileSync(configPath, "utf-8")) as ScheduleConfig;
  } catch {
    return null;
  }
}

/**
 * Compute remaining days in the current ESPN matchup period.
 *
 * ESPN fantasy baseball scoring periods increment daily (period 1 = opening day).
 * Weeks are NOT always 7 days — the opening week typically runs from Opening Day
 * through the following Sunday (e.g. Wed March 25 → Sun April 5 = 12 days).
 *
 * Three-tier approach:
 *   1. Cached schedule file (data/fantasy/schedule-{year}.json) — most reliable,
 *      generated once by `npx tsx scripts/fetch-schedule-config.ts`
 *   2. Live ESPN matchupPeriods from the API response — accurate when present
 *   3. Calendar-week fallback (Mon–Sun) — last resort, wrong for irregular weeks
 */
function computeRemainingDays(
  currentScoringPeriodId: number,
  currentMatchupPeriod: number,
  liveMatchupPeriods: Record<string, number[]> | undefined,
  seasonId: string,
  now: Date
): number {
  function remainingFromMap(map: Record<string, number[]>, source: string): number | null {
    const periods = map[String(currentMatchupPeriod)];
    if (!periods || periods.length === 0) return null;
    const lastPeriod = Math.max(...periods);
    const remaining = Math.max(1, lastPeriod - currentScoringPeriodId + 1);
    console.log(
      `[espnLoader] ${source}: scoring period ${currentScoringPeriodId}, ` +
      `week ${currentMatchupPeriod} ends at period ${lastPeriod} → ${remaining} days remaining`
    );
    return remaining;
  }

  // Tier 1: cached schedule file (generated by fetch-schedule-config.ts)
  const cached = loadScheduleConfig(seasonId);
  if (cached) {
    const result = remainingFromMap(cached.matchupPeriods, "Tier-1 [cached schedule]");
    if (result !== null) return result;
  }

  // Tier 2: live ESPN matchupPeriods from API response
  if (liveMatchupPeriods) {
    const result = remainingFromMap(liveMatchupPeriods, "Tier-2 [live ESPN]");
    if (result !== null) return result;
    console.warn("[espnLoader] Tier-2: matchupPeriods present but current week not found");
  } else {
    console.warn("[espnLoader] matchupPeriods missing from both cached file and live ESPN response");
  }

  // Tier 3: calendar week (Mon–Sun) — inaccurate for irregular weeks
  const remaining = daysRemainingInCalendarWeek(now);
  console.warn(`[espnLoader] Tier-3 [calendar fallback]: ${remaining} days remaining (run fetch-schedule-config.ts to fix this)`);
  return remaining;
}

/**
 * Estimate how many SP starts have already been used this week.
 * Uses days elapsed in the ESPN matchup period (not calendar week).
 */
function estimateStartsUsed(
  cap: number,
  daysElapsedInPeriod: number,
  periodLength: number = MATCHUP_WEEK_LENGTH_DAYS
): number {
  return Math.min(cap, Math.round(daysElapsedInPeriod * (cap / periodLength)));
}

/**
 * Builds ScheduledGame entries for the remaining days in this matchup period.
 *
 * Two modes:
 *
 * REAL SCHEDULE (preferred): when `teamSchedule` is provided, creates one entry
 * per actual MLB game. No GAME_SCHEDULED_PROB fudge needed since the game is
 * confirmed. Each entry carries opponentContext.parkFactor from the home ballpark.
 * Doubleheaders produce two entries on the same date. Off days produce no entry.
 *
 * PROBABILISTIC FALLBACK: when no schedule data is available, falls back to
 * one entry per remaining calendar day with GAME_SCHEDULED_PROB applied.
 *
 * @param remainingDays  - days left in the matchup period INCLUDING today
 * @param teamSchedule   - actual game slots from MLB Stats API (optional)
 */
function buildRemainingGames(
  role: PlayerRole,
  erosp: EROSPPlayerData | undefined,
  remainingDays: number,
  now: Date = new Date(),
  teamSchedule?: MLBGameSlot[]
): ScheduledGame[] {
  if (remainingDays <= 0) return [];

  const todayStr = toISODate(new Date(now.getFullYear(), now.getMonth(), now.getDate()));
  const games: ScheduledGame[] = [];

  // ---- Shared per-role probability helpers ----
  function roleProbs(hasConfirmedGame: boolean): {
    appearanceProbability: number;
    isStartingPitcherExpected: boolean;
    startProbability: number | undefined;
  } {
    // When the game is confirmed (real schedule), drop the GAME_SCHEDULED_PROB multiplier.
    const gameProb = hasConfirmedGame ? 1.0 : GAME_SCHEDULED_PROB;

    if (role === "hitter") {
      const pPlay = erosp?.startProbability
        ? Math.min(erosp.startProbability, 0.98)
        : HITTER_P_PLAY_DEFAULT;
      return {
        appearanceProbability: pPlay * gameProb,
        isStartingPitcherExpected: false,
        startProbability: undefined,
      };
    }

    if (role === "starting_pitcher") {
      const capAdj = erosp?.capFactor ?? 1.0;
      const pStartAdj = SP_START_RATE_PER_GAME * capAdj * gameProb;
      return {
        appearanceProbability: pStartAdj,
        isStartingPitcherExpected: true,
        startProbability: pStartAdj,
      };
    }

    // relief_pitcher
    return {
      appearanceProbability: RP_APPEARANCE_RATE_DEFAULT * gameProb,
      isStartingPitcherExpected: false,
      startProbability: undefined,
    };
  }

  // ---- Real schedule path ----
  if (teamSchedule && teamSchedule.length > 0) {
    const relevantGames = teamSchedule.filter((g) => g.date >= todayStr);

    if (relevantGames.length > 0) {
      for (const game of relevantGames) {
        const { appearanceProbability, isStartingPitcherExpected, startProbability } =
          roleProbs(true);

        games.push({
          date: game.date,
          gameState: game.date === todayStr ? "live" : "upcoming",
          locked: false,
          completed: false,
          appearanceProbability,
          isStartingPitcherExpected,
          startProbability,
          opponentContext: {
            parkFactor: game.parkFactor,
            opponentTeam: game.opponentAbbr,
          },
        });
      }
      return games;
    }
  }

  // ---- Probabilistic fallback (no schedule data) ----
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  for (let d = 0; d < remainingDays; d++) {
    const gameDate = new Date(today);
    gameDate.setDate(gameDate.getDate() + d);
    const { appearanceProbability, isStartingPitcherExpected, startProbability } =
      roleProbs(false);

    games.push({
      date: toISODate(gameDate),
      gameState: d === 0 ? "live" : "upcoming",
      locked: false,
      completed: false,
      appearanceProbability,
      isStartingPitcherExpected,
      startProbability,
    });
  }

  return games;
}

// ---- EROSP index by ESPN ID and normalized name ----

function buildEROSPIndex(players: RawEROSPPlayer[]): {
  byEspnId: Map<string, EROSPPlayerData>;
  byNormName: Map<string, EROSPPlayerData>;
} {
  const byEspnId = new Map<string, EROSPPlayerData>();
  const byNormName = new Map<string, EROSPPlayerData>();

  for (const p of players) {
    const mapped: EROSPPlayerData = {
      mlbamId: p.mlbam_id,
      espnId: p.espn_id,
      name: p.name,
      position: p.position,
      mlbTeam: p.mlb_team,
      role: p.role,
      fantasyTeamId: p.fantasy_team_id,
      isFa: p.is_fa,
      erospRaw: p.erosp_raw,
      erospStartable: p.erosp_startable,
      erospPerGame: p.erosp_per_game,
      gamesRemaining: p.games_remaining,
      startProbability: p.start_probability,
      capFactor: p.cap_factor,
      paPerGame: p.pa_per_game,
      fpPerPa: p.fp_per_pa,
    };

    if (p.espn_id) byEspnId.set(p.espn_id, mapped);
    const nn = normalizeName(p.name);
    if (!byNormName.has(nn)) byNormName.set(nn, mapped); // first match wins
  }

  return { byEspnId, byNormName };
}

function lookupEROSP(
  espnPlayerId: string,
  playerName: string,
  idx: { byEspnId: Map<string, EROSPPlayerData>; byNormName: Map<string, EROSPPlayerData> }
): EROSPPlayerData | undefined {
  return idx.byEspnId.get(espnPlayerId) ?? idx.byNormName.get(normalizeName(playerName));
}

// ---- Build a PlayerProjectionInput from ESPN roster entry + EROSP ----

function buildPlayerProjection(
  entry: ESPNAny,
  teamId: number,
  erospIdx: ReturnType<typeof buildEROSPIndex>,
  remainingDays: number,
  now: Date,
  scheduleMap?: Map<string, MLBGameSlot[]>
): PlayerProjectionInput | null {
  const ppe = entry.playerPoolEntry as ESPNAny | undefined;
  const player = ppe?.player as ESPNAny | undefined;
  if (!player) return null;

  const espnId = String(player.id ?? entry.playerId ?? "");
  const name = (player.fullName as string) ?? "Unknown";
  const defaultPositionId = (player.defaultPositionId as number) ?? 0;
  const role = toRole(defaultPositionId);

  const injuryStatus = (ppe?.injuryStatus as string) ?? "";
  const injured = ["OUT", "DOUBTFUL", "IR"].includes(injuryStatus);
  const questionable = injuryStatus === "QUESTIONABLE";

  // Lineup slot ID — 20/21 = bench, 16/17 = bench
  const lineupSlotId = (entry.lineupSlotId as number) ?? 0;
  const active = lineupSlotId < 16 || (lineupSlotId === 12); // not bench/IL

  const erosp = lookupEROSP(espnId, name, erospIdx);

  const mlbTeam = (erosp?.mlbTeam ?? (player.proTeamAbbrev as string) ?? "").toUpperCase();
  const teamSchedule = scheduleMap?.get(mlbTeam);
  const scheduledGamesRemaining = buildRemainingGames(role, erosp, remainingDays, now, teamSchedule);

  return {
    playerId: espnId,
    name,
    mlbTeam: (player.proTeamId as string) ?? "",
    fantasyTeamId: String(teamId),
    active,
    lineupSlot: String(lineupSlotId),
    role,
    injured,
    questionable,
    season: {},
    recent: {},
    erosp,
    // Set to 0: team-level currentPoints already captures the weekly total.
    // Adding per-player weekly stats on top would double-count scored points.
    alreadyScoredPointsThisMatchup: 0,
    scheduledGamesRemaining,
  };
}

// ---- Determine current SP starts used from ESPN roster data ----
// Counts SPs whose weekly appliedTotal > 0 as a proxy for starts used.
// A score > 15 suggests a quality start (QS=3, 6IP×3=18) so we count it extra.
function countStartsUsedFromRoster(players: PlayerProjectionInput[]): number {
  const sps = players.filter((p) => p.role === "starting_pitcher");
  let starts = 0;
  for (const sp of sps) {
    const pts = sp.alreadyScoredPointsThisMatchup;
    if (pts > 2) starts += 1;   // any meaningful appearance → 1 start
    if (pts > 25) starts += 1;  // excellent outing → likely 2+ starts? No, count extra start only
    // Actually: if pts > 20, likely used 2 starts (rare but possible early week start + mid-week start)
    // Capped at starts used per SP: 2 max in a 7-day week
  }
  return Math.min(starts, CBA_PITCHER_START_CAP);
}

// ---- Main loader ----

export interface LoadMatchupStateOptions {
  /** Override the season ID (defaults to ESPN_SEASON_ID env var) */
  seasonId?: string;
  /** If true, load EROSP from file; if false, projections use ESPN stats only */
  useEROSP?: boolean;
  /** Timestamp to use as "now" (for testing / nightly job timing) */
  now?: Date;
  /** Path to EROSP JSON file (defaults to data/erosp/latest.json) */
  erospPath?: string;
}

/**
 * Loads the current week's matchup states for all active matchups.
 * Combines live ESPN API data with EROSP projections.
 *
 * @returns Array of MatchupState, one per active matchup pair this week.
 */
export async function loadCurrentMatchupStates(
  options: LoadMatchupStateOptions = {}
): Promise<MatchupState[]> {
  const {
    seasonId = process.env.ESPN_SEASON_ID ?? ESPN_SEASON_ID,
    useEROSP = true,
    now = new Date(),
    erospPath,
  } = options;

  // ---- Load EROSP projections ----
  const erospFilePath =
    erospPath ??
    path.join(process.cwd(), "data", "erosp", "latest.json");

  let erospIdx: ReturnType<typeof buildEROSPIndex> = {
    byEspnId: new Map(),
    byNormName: new Map(),
  };

  if (useEROSP && fs.existsSync(erospFilePath)) {
    try {
      const erospFile: RawEROSPFile = JSON.parse(
        fs.readFileSync(erospFilePath, "utf-8")
      );
      erospIdx = buildEROSPIndex(erospFile.players);
      console.log(`[espnLoader] Loaded ${erospFile.players.length} EROSP players`);
    } catch (e) {
      console.warn("[espnLoader] Failed to load EROSP file:", e);
    }
  }

  // ---- Fetch ESPN data ----
  const client = createESPNClient(seasonId);

  // Fetch matchup scores + team/roster data in parallel
  const [matchupData, rosterData] = await Promise.all([
    client.fetchLeagueData(["mMatchup", "mMatchupScore", "mSettings", "mTeam"]),
    client.fetchLeagueData(["mTeam", "mRoster"]),
  ]);

  // ---- Parse league settings ----
  const settings = matchupData.settings as ESPNAny | undefined;
  const scoringSettings = settings?.scoringSettings as ESPNAny | undefined;

  // Pitcher start cap: try to read from ESPN settings, fall back to CBA default (7)
  const pitcherStartCap: number =
    ((scoringSettings as ESPNAny | undefined)?.allowedStartingPitchers as number) ??
    CBA_PITCHER_START_CAP;

  const leagueConfig: LeagueConfig = {
    leagueId: process.env.ESPN_LEAGUE_ID ?? ESPN_LEAGUE_ID,
    seasonId,
    scoring: CBA_SCORING,
    rosterPositions: CBA_ROSTER_SLOTS,
    pitcherStartCap,
    dailyLock: true,
    pointsLeague: true,
  };

  // ---- Determine current matchup period and remaining days ----
  const currentMatchupPeriod: number =
    ((matchupData.status as ESPNAny)?.currentMatchupPeriod as number | undefined) ??
    (matchupData.scoringPeriodId as number | undefined) ??
    1;

  const currentScoringPeriodId: number =
    (matchupData.scoringPeriodId as number | undefined) ?? 1;

  // ESPN matchupPeriods maps each matchup period to its scoring period IDs.
  // Example: { "1": [1,2,3,...,12], "2": [13,14,...,19], ... }
  const scheduleSettings = (settings as ESPNAny | undefined)?.scheduleSettings as ESPNAny | undefined;
  const matchupPeriods = scheduleSettings?.matchupPeriods as Record<string, number[]> | undefined;

  const remainingDays = computeRemainingDays(
    currentScoringPeriodId,
    currentMatchupPeriod,
    matchupPeriods,
    seasonId,
    now
  );

  // Period length for starts-used estimation
  const periodLength = matchupPeriods?.[String(currentMatchupPeriod)]?.length ?? MATCHUP_WEEK_LENGTH_DAYS;
  const daysElapsed = Math.max(0, periodLength - remainingDays);

  console.log(
    `[espnLoader] Scoring period ${currentScoringPeriodId}, matchup period ${currentMatchupPeriod}, ` +
    `${remainingDays} days remaining (period length ${periodLength})`
  );

  // Compute week start/end from scoring period for matchup config metadata
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const weekStart = new Date(today);
  weekStart.setDate(weekStart.getDate() - daysElapsed);
  const weekEnd = new Date(today);
  weekEnd.setDate(weekEnd.getDate() + remainingDays - 1);

  // ---- Build team name map ----
  const teamNameMap = new Map<number, string>();
  for (const team of (matchupData.teams ?? []) as ESPNAny[]) {
    const id = team.id as number;
    const name =
      (team.name as string) ??
      (team.location && team.nickname
        ? `${team.location} ${team.nickname}`
        : `Team ${id}`);
    teamNameMap.set(id, name);
  }

  // ---- Build roster map: teamId → player entries ----
  const rosterMap = new Map<number, ESPNAny[]>();
  for (const team of (rosterData.teams ?? []) as ESPNAny[]) {
    const teamId = team.id as number;
    const roster = team.roster as ESPNAny | undefined;
    const entries = (roster?.entries ?? []) as ESPNAny[];
    rosterMap.set(teamId, entries);
  }

  // ---- Fetch real MLB schedule for park factor + actual game counts ----
  const mlbScheduleMap = await fetchLeagueSchedule(toISODate(today), toISODate(weekEnd));
  console.log(`[espnLoader] MLB schedule: ${mlbScheduleMap.size} teams with game data`);

  // ---- Find current week's matchups ----
  const schedule = (matchupData.schedule ?? []) as ESPNAny[];
  const currentMatchups = schedule.filter(
    (m) => (m.matchupPeriodId as number) === currentMatchupPeriod
  );

  if (currentMatchups.length === 0) {
    console.warn(
      `[espnLoader] No matchups found for period ${currentMatchupPeriod}`
    );
    return [];
  }

  // ---- Build MatchupState for each matchup ----
  const results: MatchupState[] = [];

  for (const espnMatchup of currentMatchups) {
    const homeData = espnMatchup.home as ESPNAny | undefined;
    const awayData = espnMatchup.away as ESPNAny | undefined;

    if (!homeData?.teamId || !awayData?.teamId) continue;

    const homeTeamId = homeData.teamId as number;
    const awayTeamId = awayData.teamId as number;

    // Team-level current points for this week
    const homeCurrentPoints = (homeData.totalPoints as number) ?? 0;
    const awayCurrentPoints = (awayData.totalPoints as number) ?? 0;

    // Build player lists
    function buildTeamState(
      teamId: number,
      currentPoints: number
    ): FantasyTeamMatchupState {
      const entries = rosterMap.get(teamId) ?? [];
      const players: PlayerProjectionInput[] = [];

      for (const entry of entries) {
        const proj = buildPlayerProjection(entry, teamId, erospIdx, remainingDays, now, mlbScheduleMap);
        if (proj) players.push(proj);
      }

      // Estimate starts used based on days elapsed in the ESPN matchup period
      const usedPitcherStarts = estimateStartsUsed(pitcherStartCap, daysElapsed, periodLength);

      return {
        fantasyTeamId: String(teamId),
        name: teamNameMap.get(teamId) ?? `Team ${teamId}`,
        currentPoints,
        players,
        usedPitcherStarts,
      };
    }

    const homeTeam = buildTeamState(homeTeamId, homeCurrentPoints);
    const awayTeam = buildTeamState(awayTeamId, awayCurrentPoints);

    const isExtendedMatchup = periodLength > 7;

    const matchupConfig: MatchupConfig = {
      matchupId: String(espnMatchup.id ?? `${homeTeamId}-${awayTeamId}`),
      matchupPeriodId: currentMatchupPeriod,
      weekStart: toISODate(weekStart),
      weekEnd: toISODate(weekEnd),
      pitcherStartCap: isExtendedMatchup
        ? Math.ceil(pitcherStartCap * (periodLength / 7))
        : pitcherStartCap,
      isExtendedMatchup,
      lastUpdatedAt: now.toISOString(),
    };

    results.push({
      league: leagueConfig,
      matchup: matchupConfig,
      home: homeTeam,
      away: awayTeam,
    });
  }

  console.log(
    `[espnLoader] Built ${results.length} matchup states for period ${currentMatchupPeriod}`
  );
  return results;
}

/**
 * Lightweight version that loads matchup state from local JSON files only
 * (no ESPN API call). Used for backtesting and testing.
 *
 * @param homeTeamId - CBA team ID
 * @param awayTeamId - CBA team ID
 * @param homeCurrentPoints - points scored so far
 * @param awayCurrentPoints - points scored so far
 */
export async function buildOfflineMatchupState(
  homeTeamId: number,
  awayTeamId: number,
  homeCurrentPoints: number,
  awayCurrentPoints: number,
  options: LoadMatchupStateOptions = {}
): Promise<MatchupState> {
  const {
    seasonId = ESPN_SEASON_ID,
    now = new Date(),
    erospPath,
  } = options;

  const erospFilePath =
    erospPath ??
    path.join(process.cwd(), "data", "erosp", "latest.json");

  let erospIdx: ReturnType<typeof buildEROSPIndex> = {
    byEspnId: new Map(),
    byNormName: new Map(),
  };

  if (fs.existsSync(erospFilePath)) {
    const erospFile: RawEROSPFile = JSON.parse(
      fs.readFileSync(erospFilePath, "utf-8")
    );
    erospIdx = buildEROSPIndex(erospFile.players);
  }

  // Load roster data from local file
  const currentDataPath = path.join(
    process.cwd(),
    "data",
    "current",
    `${seasonId}.json`
  );
  const currentData = JSON.parse(fs.readFileSync(currentDataPath, "utf-8"));

  function buildOfflineTeam(teamId: number, currentPoints: number): FantasyTeamMatchupState {
    const rosterEntry = (currentData.rosters ?? []).find(
      (r: { teamId: number }) => r.teamId === teamId
    );
    const players: PlayerProjectionInput[] = [];

    for (const player of (rosterEntry?.players ?? [])) {
      const erosp = lookupEROSP(player.playerId ?? "", player.playerName ?? "", erospIdx);
      if (!erosp) continue;

      const role: PlayerRole =
        erosp.role === "SP"
          ? "starting_pitcher"
          : erosp.role === "RP"
          ? "relief_pitcher"
          : "hitter";

      players.push({
        playerId: player.playerId ?? "",
        name: player.playerName ?? "",
        mlbTeam: erosp.mlbTeam,
        fantasyTeamId: String(teamId),
        active: true,
        lineupSlot: erosp.position,
        role,
        season: {},
        recent: {},
        erosp,
        alreadyScoredPointsThisMatchup: 0,
        scheduledGamesRemaining: buildRemainingGames(role, erosp, offlineRemainingDays, now),
      });
    }

    return {
      fantasyTeamId: String(teamId),
      name: (currentData.teams ?? []).find((t: { id: number }) => t.id === teamId)?.name ?? `Team ${teamId}`,
      currentPoints,
      players,
      usedPitcherStarts: estimateStartsUsed(CBA_PITCHER_START_CAP, offlineDaysElapsed),
    };
  }

  const offlineRemainingDays = daysRemainingInCalendarWeek(now);
  const offlineDaysElapsed = Math.max(0, MATCHUP_WEEK_LENGTH_DAYS - offlineRemainingDays);
  const offlineWeekStart = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  offlineWeekStart.setDate(offlineWeekStart.getDate() - offlineDaysElapsed);
  const offlineWeekEnd = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  offlineWeekEnd.setDate(offlineWeekEnd.getDate() + offlineRemainingDays - 1);

  return {
    league: {
      leagueId: ESPN_LEAGUE_ID,
      seasonId,
      scoring: CBA_SCORING,
      rosterPositions: CBA_ROSTER_SLOTS,
      pitcherStartCap: CBA_PITCHER_START_CAP,
      dailyLock: true,
      pointsLeague: true,
    },
    matchup: {
      matchupId: `${homeTeamId}-${awayTeamId}`,
      matchupPeriodId: 1,
      weekStart: toISODate(offlineWeekStart),
      weekEnd: toISODate(offlineWeekEnd),
      pitcherStartCap: CBA_PITCHER_START_CAP,
      isExtendedMatchup: false,
      lastUpdatedAt: now.toISOString(),
    },
    home: buildOfflineTeam(homeTeamId, homeCurrentPoints),
    away: buildOfflineTeam(awayTeamId, awayCurrentPoints),
  };
}
